[project]
name = "energy-bills"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy==1.26.4",
    "pandas==2.3.3",
    "pipreqs>=0.5.0",
    "python-dotenv==1.0.1",
    "static==1.1.1",
    "tqdm==4.67.3",
    "vertica-python==1.4.0",
]
